version: "3.8"
services:
  megaparse:
    build:
      context: ./MegaParse
    ports:
      - "5001:5000"
    restart: always
    container_name: megaparse_service

  weaviate:
    image: semitechnologies/weaviate:1.25.4
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      DEFAULT_VECTORIZER_MODULE: "none"
      CLUSTER_HOSTNAME: "node1"
      PERSISTENCE_DATA_PATH: "./data"
    container_name: weaviate_service

  neo4j:
    image: neo4j:5.20.0
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    container_name: neo4j_service

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - megaparse
      - weaviate
      - neo4j
    restart: on-failure
    container_name: backend_service

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    restart: always
    container_name: frontend_service
