apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nagarro-backend:mvp
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: api-keys-secret
          env:
            - name: LLM_PROVIDER
              value: "openai" # or "anthropic" or "google"
            - name: PROJECT_SERVICE_URL
              value: "http://project-service:8000"
            - name: WEAVIATE_URL
              value: "http://weaviate-service:8080"
            - name: NEO4J_URL
              value: "bolt://neo4j-service:7687"
            - name: NEO4J_USER
              value: "neo4j"
            - name: NEO4J_PASSWORD
              value: "password"
            - name: REPORTING_SERVICE_URL
              value: "http://reporting-service:8000"
            - name: OBJECT_STORAGE_ENDPOINT
              value: "minio-service:9000"
            - name: OBJECT_STORAGE_ACCESS_KEY
              value: "minioadmin"
            - name: OBJECT_STORAGE_SECRET_KEY
              value: "minioadmin"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30801
