apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting-service
  template:
    metadata:
      labels:
        app: reporting-service
    spec:
      containers:
        - name: reporting-service
          image: reporting-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://projectuser:projectpass@postgres-service:5432/projectdb"
            - name: PROJECT_SERVICE_URL
              value: "http://project-service:8000"
            - name: OBJECT_STORAGE_ENDPOINT
              value: "minio-service:9000"
            - name: OBJECT_STORAGE_ACCESS_KEY
              value: "minioadmin"
            - name: OBJECT_STORAGE_SECRET_KEY
              value: "minioadmin"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: reporting-service
spec:
  type: NodePort
  selector:
    app: reporting-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30803
