apiVersion: v1
kind: Secret
metadata:
  name: api-keys-secret
type: Opaque
data:
  OPENAI_API_KEY: 
  GOOGLE_API_KEY: QUl6YVN5QVl4RjRNRkNvOS1OSkhhQlF4V0VDX3V2RXRNaGZYSktzIA==
  ANTHROPIC_API_KEY: 
# Replace the above values with your actual base64-encoded API keys for each provider
